site_name: GroupsMath
site_description: The educational Python library for Group Theory
site_author: Mario Sultan

theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Basic group methods:
      - Groups: Groups.md
      - Group families and precooked groups: Group_families_and_precooked_groups.md
      - Group operations and properties: Group_operations_and_properties.md
      - Elements: Elements.md
      - Cayley table visualization: Cayley_table_visualization.md
  - Advanced group methods:
      - Subgroups: Subgroups.md
      - Automorphisms: Automorphisms.md
      - Products: Products.md
      - Conjugation and commutators: Conjugation_and_commutators.md
  - Matrix groups:
      - Matrix groups: Matrix_groups.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
